feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -96,11 +96,12 @@
           fi || exit 1
           echo "Tag extracted: $GENERATED_TAG"
 
-      # - "if [ -z \"$GENERATED_TAG\" ]; then echo \"Error: Generated tag is empty.\"; exit 1; else echo \"Tag extracted: $GENERATED_TAG\"; fi || exit 1"
-      # - 'echo "Tag extracted: $GENERATED_TAG"'
-
-      # - echo "Checking if GENERATED_TAG satisfies the <feature>-<feature-name>-<size> format..."
-      # - if [ -z "$GENERATED_TAG" ]; then echo "Commit violates <feature>-<feature-name>-<size> format required for proper docker image tagging"; exit 1; fi
+      - |
+        echo "Checking if GENERATED_TAG satisfies the <feature>-<feature-name>-<size> format..."
+        if [ -z "$GENERATED_TAG" ]; then
+            echo "Commit violates <feature>-<feature-name>-<size> format required for proper docker image tagging";
+            exit 1;
+        fi
 
       # - echo "Using docker-compose to build the updated images in the repository..."
       # - docker-compose -f docker-compose.yaml build --no-cache || exit 1
