feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -121,7 +121,14 @@
             exit 1;
         fi
 
-      # - if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then echo "Server Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
+      - |
+        if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then
+            echo "Server Image successfully pushed to DockerHub";
+        else
+            echo "Failed to push image to DockerHub";
+            exit 1;
+        fi
+
 
       # - if docker push $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG; then echo "Database Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
       # - ssh root@$DROPLET_IP "echo 'GENERATED_TAG=$GENERATED_TAG' > /root/sang-logium/.env"
