feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -62,7 +62,7 @@
         echo "Installing necessary dependencies..."
         apk add --no-cache docker-compose openssh-client
         echo "Checking if docker-compose is installed..."
-        docker-compose --version
+        docker-compose --version || echo "Error: docker-compose is not installed or failed to execute."
 
       - |
         echo "Logging into DockerHub..."
