feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -107,13 +107,13 @@
         - docker:dind
 
       before_script:
-        - echo "Deploying as ${GITLAB_USER_LOGIN}"
-        - echo "CI_COMMIT_TAG -> ${CI_COMMIT_TAG}"
-        - echo "CI_COMMIT_MESSAGE -> ${CI_COMMIT_MESSAGE}"
-        - echo "GENERATED_TAG -> ${GENERATED_TAG}"
-
-
-
+        - |
+          if [ -z "$GENERATED_TAG" ]; then
+              echo "Error: Generated tag is empty.";
+              exit 1;
+          fi
+        - echo "GENERATED_TAG for docker images is '${GENERATED_TAG}'"
+        - echo "DOCKER_HUB_USERNAME -> ${DOCKER_HUB_USERNAME}"
         - |
           echo "Installing necessary dependencies..."
           apk add --no-cache docker-compose openssh-client
