feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -138,14 +138,30 @@
             exit 1;
         fi
 
-        - |
-          ssh root@$DROPLET_IP "bash -c '\
-          echo \"GENERATED_TAG=$GENERATED_TAG\" > /root/sang-logium/.env && \
-          docker pull $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG || { echo \"Failed to pull frontend image\"; exit 1; } && \
-          docker pull $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG || { echo \"Failed to pull server image\"; exit 1; } && \
-          docker pull $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG || { echo \"Failed to pull database image\"; exit 1; } && \
-          docker-compose -f /root/sang-logium/docker-compose.yaml up -d || { echo \"Failed to start services with docker-compose\"; exit 1; } \
-        '"
+      - ./deploy.sh
+
+      # - |
+      #   ssh root@$DROPLET_IP "bash -c '\
+      #   echo \"GENERATED_TAG=$GENERATED_TAG\" > /root/sang-logium/.env && \
+      #   scp /root/sang-logium/.env root@$DROPLET_IP:/root/sang-logium/.env
+
+      #   sed -e "s/\${MONGO_INITDB_ROOT_USERNAME}/$MONGO_INITDB_ROOT_USERNAME/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   sed -e "s/\${MONGO_INITDB_ROOT_PASSWORD}/$MONGO_INITDB_ROOT_PASSWORD/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   sed -e "s/\${MONGO_INITDB_DATABASE}/$MONGO_INITDB_DATABASE/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   sed -e "s/\${MONGO_URI}/$MONGO_URI/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   sed -e "s/\${DATA_SERVER_NODE_ENV}/$DATA_SERVER_NODE_ENV/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   sed -e "s/\${DATA_SERVER_PORT}/$DATA_SERVER_PORT/g" /path/to/docker-compose.yaml.template > /root/sang-logium/docker-compose.yaml
+
+      #   docker pull $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG || { echo \"Failed to pull frontend image\"; exit 1; } && \
+      #   docker pull $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG || { echo \"Failed to pull server image\"; exit 1; } && \
+      #   docker pull $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG || { echo \"Failed to pull database image\"; exit 1; } && \
+      #   docker-compose -f /root/sang-logium/docker-compose.yaml up -d || { echo \"Failed to start services with docker-compose\"; exit 1; } \
+      #   '"
 
       # - ssh root@$DROPLET_IP "echo 'GENERATED_TAG=$GENERATED_TAG' > /root/sang-logium/.env"
       # - ssh root@$DROPLET_IP "docker pull $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG || echo 'Failed to pull frontend image'; exit 1"
