feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -113,7 +113,13 @@
           echo "Pushing the built images with the generated tag: $GENERATED_TAG"
 
 
-      # - if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then echo "Frontend Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
+      - |
+        if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then
+            echo "Frontend Image successfully pushed to DockerHub";
+        else
+            echo "Failed to push image to DockerHub";
+            exit 1;
+        fi
 
       # - if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then echo "Server Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
 
