feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -78,15 +78,15 @@
       - export GENERATED_TAG=$(cat tag.txt)
 
       - echo "Checking for tag.txt file..."
-      - if [ ! -f "tag.txt" ] || [ ! -s "tag.txt" ]; then echo "tag.txt file is missing or empty"; exit 1; fi
+      - if [ ! -f "tag.txt" ] || [ ! -s "tag.txt" ]; then echo "tag.txt file is missing or empty"; exit 1; fi || exit 1
 
       - echo "Ensuring tag.txt is not empty..."
-      - "if [ ! -s 'tag.txt' ]; then echo 'Error: tag.txt file is empty.'; exit 1; fi"
+      - "if [ ! -s 'tag.txt' ]; then echo 'Error: tag.txt file is empty.'; exit 1; fi || exit 1"
 
       - echo "Reading GENERATED_TAG from tag.txt..."
-      - export GENERATED_TAG=$(cat tag.txt)
+      - export GENERATED_TAG=$(cat tag.txt) || exit 1
 
-      - "if [ -z \"$GENERATED_TAG\" ]; then echo \"Error: Generated tag is empty.\"; exit 1; else echo \"Tag extracted: $GENERATED_TAG\"; fi"
+      - "if [ -z \"$GENERATED_TAG\" ]; then echo \"Error: Generated tag is empty.\"; exit 1; else echo \"Tag extracted: $GENERATED_TAG\"; fi || exit 1"
       - 'echo "Tag extracted: $GENERATED_TAG"'
 
       - echo "Checking if GENERATED_TAG satisfies the <feature>-<feature-name>-<size> format..."
@@ -94,23 +94,23 @@
 
       - echo "Using docker-compose to build the updated images in the repository..."
       - docker image rm munrhalls/sang-logium-frontend:latest -f
-      - docker-compose -f docker-compose.yaml build --no-cache sang-logium-frontend
+      - docker-compose -f docker-compose.yaml build --no-cache sang-logium-frontend || exit 1
 
       - "echo Tagging the built image with the generated tag: $GENERATED_TAG"
-      - docker tag $DOCKER_HUB_USERNAME/sang-logium-frontend $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG
+      - docker tag $DOCKER_HUB_USERNAME/sang-logium-frontend $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG || exit 1
 
       - "echo DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME"
       - "echo GENERATED_TAG: $GENERATED_TAG"
       - "echo Pushing the built image with the generated tag: $GENERATED_TAG"
-      - if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then echo "Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; fi
+      - if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then echo "Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; fi || exit 1
 
       - "echo SSH into the droplet, pull the latest image, and run docker-compose to update the services..."
       - |
-        ssh root@$DROPLET_IP "
+        ssh root@$DROPLET_IP || exit 1"
         echo 'GENERATED_TAG=$GENERATED_TAG' > /root/sang-logium/.env && \
         echo 'The .env file on DROPLET PC updated successfully' && \
         docker pull $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG && \
         docker-compose -f /root/sang-logium/docker-compose.yaml up -d
-        "
+        || exit 1"
     only:
     - main
