feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -74,14 +74,16 @@
         - echo "SSH INTO DROPLET"
         - eval $(ssh-agent -s)
 
-        - echo "Add droplet IP to ssh known hosts to avoid interactive prompt"
-        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-        - mkdir -p ~/.ssh
-        - chmod 700 ~/.ssh
+        - echo "Add droplet IP to ssh known hosts to avoid   interactive prompt"
+        - |
+          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
 
         - echo "Add droplet IP to known hosts to avoid interactive prompt"
-        - ssh-keyscan -v $DROPLET_IP >> ~/.ssh/known_hosts || echo "ssh-keyscan failed with exit code $?"
-        - chmod 644 ~/.ssh/known_hosts
+        - |
+          ssh-keyscan -v $DROPLET_IP >> ~/.ssh/known_hosts || echo "ssh-keyscan failed with exit code $?"
+          chmod 644 ~/.ssh/known_hosts
 
       script:
         - |
@@ -91,25 +93,17 @@
         - echo "Pushing the built images with the tag '${GENERATED_TAG}"
         - docker-compose -f docker-compose.yaml push
 
-        # - |
-        #   ssh root@$DROPLET_IP <<EOF
-        #     echo "Stopping containers..."
-        #     cd /root/sang-logium
-        #     docker-compose down
-        #   EOF
+        - |
+          ssh root@$DROPLET_IP <<EOF
+            echo "Stopping containers..."
+            cd /root/sang-logium
+            docker-compose down
+          EOF
 
-        # - echo "SSH into Droplet PC, pull and build updated images using docker-compose"
-        # - scp ./docker-compose.yaml root@$DROPLET_IP:/root/sang-logium/docker-compose.yaml
+        - scp ./docker-compose.yaml root@$DROPLET_IP:/root/sang-logium/docker-compose.yaml
 
         - |
           ssh root@$DROPLET_IP <<EOF
-            echo "Stopping containers to ensure clean environment"
-            cd /root/sang-logium
-            docker-compose down
-            echo "Transferring docker-compose.yaml..."
-            cat > /root/sang-logium/docker-compose.yaml <<EOT
-            $(cat ./docker-compose.yaml)
-            EOT
             export GENERATED_TAG=${GENERATED_TAG}
             export MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
             export MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
@@ -117,7 +111,7 @@
             export MONGO_URI=${MONGO_URI}
             export DATA_SERVER_NODE_ENV=${DATA_SERVER_NODE_ENV}
             export DATA_SERVER_PORT=${DATA_SERVER_PORT}
-            echo "Pulling and starting containers..."
+            cd /root/sang-logium
             docker-compose pull && docker-compose up -d
           EOF
 
