feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,191 +1,199 @@
-  stages:
-    # - pre-flight-checks
-    - prepare
-    # - test_build
-    - deploy
+    stages:
+      # - pre-flight-checks
+      - prepare
+      # - test_build
+      - deploy
 
 
-  # pre_flight_checks:
-  #   stage: pre-flight-checks
-  #   image: docker:25.0.3-dind-alpine3.19
-  #   services:
-  #     - docker:dind
-    # script:
-      # - |
-      #     echo "Directory Existence and Content Validation"
-      #     if [ ! -d "/root/sang-logium/database" ]; then
-      #       echo "Database directory '/root/sang-logium/database' not found"
-      #       exit 1
-      #     fi
-      #     if [ -z "$(ls -A /root/sang-logium/database)" ]; then
-      #       echo "Database directory '/root/sang-logium/database' is empty."
-      #       exit 1
-      #     fi
-      #     ls -ld /root/sang-logium/database || { echo "Cannot access database directory '/root/sang-logium/database'."; exit 1; }
-      # - |
-      #   echo "Docker Daemon Availability Check"
-      #   docker info > /dev/null 2>&1
-      #   if [ $? -ne 0 ]; then
-      #     echo "Docker daemon not running."
-      #     exit 1
-      #   fi
-      # - |
-      #   # Environment Variables Validation
-      #   required_vars=("VARIABLE_1" "VARIABLE_2" "VARIABLE_3")  # Replace these with actual variable names
-      #   for var in "${required_vars[@]}"; do
-      #     if [ -z "${!var}" ]; then  # Indirect parameter expansion to check if variable is set
-      #       echo "$var is not set."
-      #       exit 1
-      #     fi
-      #   done
+    # pre_flight_checks:
+    #   stage: pre-flight-checks
+    #   image: docker:25.0.3-dind-alpine3.19
+    #   services:
+    #     - docker:dind
+      # script:
+        # - |
+        #     echo "Directory Existence and Content Validation"
+        #     if [ ! -d "/root/sang-logium/database" ]; then
+        #       echo "Database directory '/root/sang-logium/database' not found"
+        #       exit 1
+        #     fi
+        #     if [ -z "$(ls -A /root/sang-logium/database)" ]; then
+        #       echo "Database directory '/root/sang-logium/database' is empty."
+        #       exit 1
+        #     fi
+        #     ls -ld /root/sang-logium/database || { echo "Cannot access database directory '/root/sang-logium/database'."; exit 1; }
+        # - |
+        #   echo "Docker Daemon Availability Check"
+        #   docker info > /dev/null 2>&1
+        #   if [ $? -ne 0 ]; then
+        #     echo "Docker daemon not running."
+        #     exit 1
+        #   fi
+        # - |
+        #   # Environment Variables Validation
+        #   required_vars=("VARIABLE_1" "VARIABLE_2" "VARIABLE_3")  # Replace these with actual variable names
+        #   for var in "${required_vars[@]}"; do
+        #     if [ -z "${!var}" ]; then  # Indirect parameter expansion to check if variable is set
+        #       echo "$var is not set."
+        #       exit 1
+        #     fi
+        #   done
 
-  variables:
-    GIT_DEPTH: "0"
-  generate_tag:
-    stage: prepare
-    script:
-      - chmod +x ./parseCommitToTag.sh
-      - ./parseCommitToTag.sh > tag.txt
-    artifacts:
-      paths:
-        - tag.txt
+    variables:
+      GIT_DEPTH: "0"
+    generate_tag:
+      stage: prepare
+      script:
+        - chmod +x ./parseCommitToTag.sh
+        - ./parseCommitToTag.sh > tag.txt
+      artifacts:
+        paths:
+          - tag.txt
 
-  # test_build_server:
-  #   stage: test_build
-  #   image: node:20.10.0-alpine
-  #   cache:
-  #     key: ${CI_COMMIT_REF_SLUG}-node-modules
-  #     paths:
-  #       - frontend/node_modules/
-  #   script:
-  #     - cd server
-  #     - npm ci
-  #     - npm run test
-  #     - npm run lint
+    # test_build_server:
+    #   stage: test_build
+    #   image: node:20.10.0-alpine
+    #   cache:
+    #     key: ${CI_COMMIT_REF_SLUG}-node-modules
+    #     paths:
+    #       - frontend/node_modules/
+    #   script:
+    #     - cd server
+    #     - npm ci
+    #     - npm run test
+    #     - npm run lint
 
-  # test_build_frontend:
-  #   stage: test_build
-  #   image: node:20.10.0-alpine
-  #   cache:
-  #     key: ${CI_COMMIT_REF_SLUG}-node-modules
-  #     paths:
-  #       - frontend/node_modules/
-  #   script:
-  #     - cd frontend
-  #     - npm ci
-  #     - npm install --save-dev @angular/cli
-  #     - apk update && apk add chromium
-  #     - export CHROME_BIN=/usr/bin/chromium-browser
-  #     # Set CHROME_BIN to the path of the installed Chromium binary
-  #     - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
-  #     - npm run lint
-  #     - npx ng build --configuration=production
+    # test_build_frontend:
+    #   stage: test_build
+    #   image: node:20.10.0-alpine
+    #   cache:
+    #     key: ${CI_COMMIT_REF_SLUG}-node-modules
+    #     paths:
+    #       - frontend/node_modules/
+    #   script:
+    #     - cd frontend
+    #     - npm ci
+    #     - npm install --save-dev @angular/cli
+    #     - apk update && apk add chromium
+    #     - export CHROME_BIN=/usr/bin/chromium-browser
+    #     # Set CHROME_BIN to the path of the installed Chromium binary
+    #     - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
+    #     - npm run lint
+    #     - npx ng build --configuration=production
 
-    # artifacts:
-    #   paths:
-    #     - frontend/dist/
+      # artifacts:
+      #   paths:
+      #     - frontend/dist/
 
-  deploy:
-    stage: deploy
-    image: docker:25.0.3-dind-alpine3.19
-    services:
-      - docker:dind
 
-    before_script:
-      - |
-        echo "Installing necessary dependencies..."
-        apk add --no-cache docker-compose openssh-client
-        echo "Checking if docker-compose is installed..."
-        docker-compose --version || echo "Error: docker-compose is not installed or failed to execute."
+    terraform_init:
+      stage: deploy
+      script:
+        - terraform init
+      only:
+        - main
 
-      - |
-        echo "Logging into DockerHub..."
-        echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
+    deploy:
+      stage: deploy
+      image: docker:25.0.3-dind-alpine3.19
+      services:
+        - docker:dind
 
-      - |
-        echo "SSH INTO DROPLET"
-        eval $(ssh-agent -s)
+      before_script:
+        - |
+          echo "Installing necessary dependencies..."
+          apk add --no-cache docker-compose openssh-client
+          echo "Checking if docker-compose is installed..."
+          docker-compose --version || echo "Error: docker-compose is not installed or failed to execute."
 
-      - |
-        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
-        mkdir -p ~/.ssh
-        chmod 700 ~/.ssh
+        - |
+          echo "Logging into DockerHub..."
+          echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
 
-      - |
-        echo "Add droplet IP to known hosts to avoid interactive prompt"
-        ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
-        chmod 644 ~/.ssh/known_hosts
+        - |
+          echo "SSH INTO DROPLET"
+          eval $(ssh-agent -s)
 
-      - chmod +x ./deployValidate.sh
-      - chmod +x ./deploy.sh
+        - |
+          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
 
-    script:
-      # TAG IT
-      - |
-        echo "Checking for tag.txt file..."
-        if [ ! -f "tag.txt" ] || [ ! -s "tag.txt" ]; then
-          echo "Error: tag.txt file is missing or empty"
-          exit 1
-        fi
+        - |
+          echo "Add droplet IP to known hosts to avoid interactive prompt"
+          ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
 
-      - |
-        echo "Reading GENERATED_TAG from tag.txt..."
-        export GENERATED_TAG=$(cat tag.txt) || exit 1
+        - chmod +x ./deployValidate.sh
+        - chmod +x ./deploy.sh
 
-      - |
+      script:
+        # GET TAG
+        - |
+          echo "Checking for tag.txt file..."
+          if [ ! -f "tag.txt" ] || [ ! -s "tag.txt" ]; then
+            echo "Error: tag.txt file is missing or empty"
+            exit 1
+          fi
+
+        - |
+          echo "Reading GENERATED_TAG from tag.txt..."
+        - export GENERATED_TAG=$(terraform output -raw GENERATED_TAG) || exit 1
+
+        - |
+            if [ -z "$GENERATED_TAG" ]; then
+              echo "Error: Generated tag is empty.";
+              exit 1;
+            else
+              echo "Tag extracted: $GENERATED_TAG";
+            fi || exit 1
+            echo "Tag extracted: $GENERATED_TAG"
+
+        - |
+          echo "Checking if GENERATED_TAG satisfies the <feature>-<feature-name>-<size> format..."
           if [ -z "$GENERATED_TAG" ]; then
-            echo "Error: Generated tag is empty.";
-            exit 1;
+              echo "Commit violates <feature>-<feature-name>-<size> format required for proper docker image tagging";
+              exit 1;
+          fi
+
+
+        # BUILD & PUSH IMAGES
+        - |
+          echo "Using docker-compose to build the updated images in the repository..."
+          docker-compose -f docker-compose.yaml build --no-cache || exit 1
+
+        - |
+            echo DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
+            echo GENERATED_TAG: $GENERATED_TAG
+            echo "Pushing the built images with the generated tag: $GENERATED_TAG"
+
+        - |
+          if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then
+              echo "Frontend Image successfully pushed to DockerHub";
           else
-            echo "Tag extracted: $GENERATED_TAG";
-          fi || exit 1
-          echo "Tag extracted: $GENERATED_TAG"
+              echo "Failed to push image to DockerHub";
+              exit 1;
+          fi
 
-      - |
-        echo "Checking if GENERATED_TAG satisfies the <feature>-<feature-name>-<size> format..."
-        if [ -z "$GENERATED_TAG" ]; then
-            echo "Commit violates <feature>-<feature-name>-<size> format required for proper docker image tagging";
-            exit 1;
-        fi
+        - |
+          if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then
+              echo "Server Image successfully pushed to DockerHub";
+          else
+              echo "Failed to push image to DockerHub";
+              exit 1;
+          fi
 
+        - |
+          if docker push $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG; then
+              echo "Database Image successfully pushed to DockerHub";
+          else
+              echo "Failed to push image to DockerHub";
+              exit 1;
+          fi
 
-       # BUILD & PUSH IMAGES
-      - |
-        echo "Using docker-compose to build the updated images in the repository..."
-        docker-compose -f docker-compose.yaml build --no-cache || exit 1
+        - pwd
+        - ls -la
+        - ./deploy.sh
 
-      - |
-          echo DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
-          echo GENERATED_TAG: $GENERATED_TAG
-          echo "Pushing the built images with the generated tag: $GENERATED_TAG"
-
-      - |
-        if docker push $DOCKER_HUB_USERNAME/sang-logium-frontend:$GENERATED_TAG; then
-            echo "Frontend Image successfully pushed to DockerHub";
-        else
-            echo "Failed to push image to DockerHub";
-            exit 1;
-        fi
-
-      - |
-        if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then
-            echo "Server Image successfully pushed to DockerHub";
-        else
-            echo "Failed to push image to DockerHub";
-            exit 1;
-        fi
-
-      - |
-        if docker push $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG; then
-            echo "Database Image successfully pushed to DockerHub";
-        else
-            echo "Failed to push image to DockerHub";
-            exit 1;
-        fi
-
-      - pwd
-      - ls -la
-      - ./deploy.sh
-
-    only:
-      - main
+      only:
+        - main
