feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -104,16 +104,22 @@
       # - if docker push $DOCKER_HUB_USERNAME/sang-logium-server:$GENERATED_TAG; then echo "Server Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
 
       # - if docker push $DOCKER_HUB_USERNAME/sang-logium-database:$GENERATED_TAG; then echo "Database Image successfully pushed to DockerHub"; else echo "Failed to push image to DockerHub"; exit 1; fi
-      - ssh root@$DROPLET_IP <<EOF
-        echo 'GENERATED_TAG=\$GENERATED_TAG' > /root/sang-logium/.env &&
+      # - ssh root@$DROPLET_IP <<EOF
+      #   echo 'GENERATED_TAG=\$GENERATED_TAG' > /root/sang-logium/.env &&
 
+      #   docker-compose -f /root/sang-logium/docker-compose.yaml up -d || { echo 'Failed to start services with docker-compose'; exit 1; }
+      #   EOF
+
+    # only:
+    #   - main
+
+      - ssh root@$DROPLET_IP <<EOF
+        echo 'GENERATED_TAG=$GENERATED_TAG' > /root/sang-logium/.env &&
         docker-compose -f /root/sang-logium/docker-compose.yaml up -d || { echo 'Failed to start services with docker-compose'; exit 1; }
         EOF
 
     only:
       - main
-
-
 # docker pull $DOCKER_HUB_USERNAME/sang-logium-frontend:\$GENERATED_TAG || { echo 'Failed to pull frontend image'; exit 1; } &&
         # docker pull $DOCKER_HUB_USERNAME/sang-logium-server:\$GENERATED_TAG || { echo 'Failed to pull server image'; exit 1; } &&
         # docker pull $DOCKER_HUB_USERNAME/sang-logium-database:\$GENERATED_TAG || { echo 'Failed to pull database image'; exit 1; } &&
