feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -87,22 +87,22 @@
       #   paths:
       #     - frontend/dist/
 
-    # generate_tag_for_deployed_images:
-    #   stage: prepare
-    #   script:
-    #   # IMPORTANT: NOT GIT TAGS. This tag is parsed commit message.
-    #   - chmod +x ./parseCommitToTag.sh
-    #   - echo "GENERATED_TAG=$(./parseCommitToTag.sh)" >> tag.env
-    #   - echo "GENERATED_TAG for docker images is '${GENERATED_TAG}'"
-    #   - |
-    #     if [ -z "$GENERATED_TAG" ]; then
-    #         echo "Error: Generated tag is empty.";
-    #         exit 1;
-    #     fi
-    #     script:
-    #     artifacts:
-    #       reports:
-    #         dotenv: tag.env
+    generate_tag_for_deployed_images:
+      stage: prepare
+      script:
+      # IMPORTANT: NOT A GIT TAG, this tag is parsed commit message.
+      - chmod +x ./parseCommitToTag.sh
+      - echo "GENERATED_TAG=$(./parseCommitToTag.sh)" >> tag.env
+      - echo "GENERATED_TAG for docker images is '${GENERATED_TAG}'"
+      - |
+        if [ -z "$GENERATED_TAG" ]; then
+            echo "Error: Generated tag is empty.";
+            exit 1;
+        fi
+        script:
+        artifacts:
+          reports:
+            dotenv: tag.env
 
     deploy:
       stage: deploy
@@ -111,8 +111,6 @@
         - docker:dind
 
       before_script:
-        - chmod +x ./parseCommitToTag.sh
-        - echo "GENERATED_TAG=$(./parseCommitToTag.sh)"
         - |
           if [ -z "$GENERATED_TAG" ]; then
               echo "Error: Generated tag is empty.";
