feature-ci/cd-tiny

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -105,29 +105,29 @@
 
         - |
           ssh -v root@$DROPLET_IP <<'EOF'
-          set -e  # Exit immediately if a command exits with a non-zero status
-          echo "Starting deployment process..."
+            set -e  # Exit immediately if a command exits with a non-zero status
+            echo "Starting deployment process..."
 
-          # Export environment variables
-          echo "Exporting environment variables..."
-          export GENERATED_TAG='${GENERATED_TAG}'
-          export MONGO_INITDB_ROOT_USERNAME='${MONGO_INITDB_ROOT_USERNAME}'
-          export MONGO_INITDB_ROOT_PASSWORD='${MONGO_INITDB_ROOT_PASSWORD}'
-          export MONGO_INITDB_DATABASE='${MONGO_INITDB_DATABASE}'
-          export MONGO_URI='${MONGO_URI}'
-          export DATA_SERVER_NODE_ENV='${DATA_SERVER_NODE_ENV}'
-          export DATA_SERVER_PORT='${DATA_SERVER_PORT}'
+            # Export environment variables
+            echo "Exporting environment variables..."
+            export GENERATED_TAG='${GENERATED_TAG}'
+            export MONGO_INITDB_ROOT_USERNAME='${MONGO_INITDB_ROOT_USERNAME}'
+            export MONGO_INITDB_ROOT_PASSWORD='${MONGO_INITDB_ROOT_PASSWORD}'
+            export MONGO_INITDB_DATABASE='${MONGO_INITDB_DATABASE}'
+            export MONGO_URI='${MONGO_URI}'
+            export DATA_SERVER_NODE_ENV='${DATA_SERVER_NODE_ENV}'
+            export DATA_SERVER_PORT='${DATA_SERVER_PORT}'
 
-          # Navigate to the project directory
-          echo "Navigating to the project directory..."
-          cd /root/sang-logium || exit 1  # Exit if the directory does not exist
+            # Navigate to the project directory
+            echo "Navigating to the project directory..."
+            cd /root/sang-logium || exit 1  # Exit if the directory does not exist
 
-          # Pull and start containers
-          echo "Pulling and starting containers..."
-          docker-compose pull || exit 1  # Exit if docker-compose pull fails
-          docker-compose up -d || exit 1  # Exit if docker-compose up fails
+            # Pull and start containers
+            echo "Pulling and starting containers..."
+            docker-compose pull || exit 1  # Exit if docker-compose pull fails
+            docker-compose up -d || exit 1  # Exit if docker-compose up fails
 
-          echo "Deployment process completed successfully."
+            echo "Deployment process completed successfully."
           EOF
 
       only:
